### ISSUE TITLE
version 1.0

### ISSUE THREAD

**Issue by egarics** [muzuiget/dualsub-support#67] opened 2020-05-09 06:23 UTC
First of all thank you for old version of dualsub.
new version work bad for me:
1. English sub timeline in extension doesn't match neither original YouTube English sub nor Russian translation. Old version had worked fine
2. I need to choose droopdown options on every videos every time I start new video but old version had worked fine totally automatic.

can I get old version?

**Comment by muzuiget** [comment] 2020-05-09 09:40
1 .Please provides a testing video url.
2. This feature will add in future version.

You can get the old version from Firefox, because new version drop support it.

**Comment by egarics** [comment] 2020-05-10 15:48
![image](https://user-images.githubusercontent.com/40699098/81503898-d6182600-92ee-11ea-98ba-057e89cb09f2.png)

**Comment by muzuiget** [comment] 2020-05-10 22:36
Please provide the video url.

**Comment by muzuiget** [comment] 2020-05-12 01:11
I can reproduce this bug on auto-generate type subtitle

**Comment by muzuiget** [comment] 2020-05-13 00:28
This fixed in v1.1.3

**Closed by muzuiget** 2020-05-13 00:28 UTC

**Comment by egarics** [comment] 2020-05-13 06:52
it works, thank you!!!
