### ISSUE TITLE
Please support https://www.amazon.co.jp

### ISSUE THREAD

**Issue by aaron13100** [muzuiget/dualsub-support#357] opened 2021-12-10 08:19 UTC
_Website URL:_ **https://www.amazon.co.jp**

_Test videos:_  **Most videos only have Japanese subtitles. For example https://www.amazon.co.jp/gp/video/detail/B09KN8F14R/**

thanks

_Whether the videos are free to watch._
**No.**

_If the videos are paid to watch, are there any free episodes for trial?_
**Probably, but you have to be in Japan or use a VPN like Nord VPN.**

_Whether it will distinguish the viewer, such as add extra restrictions according to the viewer's location or device?_
**Yes.**

_The technical complexity of the website, such as single-page application, subtitle format._
**I have no idea, but maybe it's the same as other amazon sites.**

_Legal issues._
**I don't know.**

thanks

**Comment by muzuiget** [comment] 2021-12-11 19:31
I am sorry to tell you that kind of domain that contains `amazon` are won't be supported, eg: `amazon.co.jp`、`amazon.com`.

See https://github.com/muzuiget/dualsub-support/issues/194#issuecomment-835810064 for reason.

**Comment by aaron13100** [comment] 2021-12-11 22:00
Thank you for your reply. 

Can you provide a version that allows this? Can you provide a workaround?
Prime Video does not work in Japan with the URL primevideo.com. (See screenshot below).

According to [https://www.howtogeek.com/fyi/how-to-control-a-chrome-extensions-permissions/](https://www.howtogeek.com/fyi/how-to-control-a-chrome-extensions-permissions/#:~:text=You%20can%20now%20control%20the%20specific%20list%20of%20sites%20the%20extension%20can%20access%20from%20the%20%E2%80%9CAllowed%20sites%E2%80%9D%20list.) extension permissions can be set per-site. Is this not something that would help in this situation? 

thanks

![Screen Shot 2021-12-11 at 22 51 02](https://user-images.githubusercontent.com/16979849/145692738-b410566e-c457-4afe-9f9b-174c14dc57bd.jpg)

**Comment by muzuiget** [comment] 2021-12-12 01:04
To support `amazon.co.jp`, we need to resolve 2 issues.

**1. Users/Your side: Add the extension host permission**

Yes, there is a workaround, you can extract the extension .crx file to a directory, then edit the `manifest.json` to add the host permisson `amazon.co.jp`, then load it with the developer mode.

**2. Developers/My side: Add the website adaptation code**

Ideally, the adaptation code of `primervideo.com` can be reused for `amazon.co.jp`, but I am not sure if it works, I need to test.

But I can't access `amazon.co.jp`:

1. I need a `amazon.co.jp` account.
2. I need Japan proxy.

I can borrow  a account from a users. But as I said in previous comment, An Amazon account may contains sensitive information, eg: living address or credit card, Users may be reluctant to share such accounts. The Netflix account does not have this issue, because it is purely a streaming site.

I also need a Japan proxy, generally I can rent to Tokyo server on Google Cloud Platform, but this may not works, because the website knows that this is not a home IP, it knows that you are using a proxy, and therefore refuses access.

So it is very difficult to support streaming media sites in Japan. I need help from someone who really lives in Japan. If you want to use Dualsub on a Japanese streaming site, we can communicate further via email.

**Comment by aaron13100** [comment] 2021-12-12 22:55
Hey. I unzipped the crx file and added https://www.amazon.co.jp/* to the manifest. 

![Screen Shot 2021-12-12 at 23 32 32](https://user-images.githubusercontent.com/16979849/145732170-13f603fb-1887-49fa-96c7-c266cdd01b18.jpg)

The plugin seems to not detect the subtitles. There's a javascript error: 

![Screen Shot 2021-12-12 at 23 34 06](https://user-images.githubusercontent.com/16979849/145732277-ea5c6ab8-2343-4a14-826d-3a13fdbbcd02.jpg)

I used a deobfuscator on content.js and added the line 
> if ("www.amazon.co.jp" === e) return "primevideo";

where it was needed. 

I retested and it seems to work fine. There seemed to be some timing issues during the show introduction, when the scene changed quickly and it was kind of a recap of the previous episodes and a preview of the current episode. Once the current episode actually started then the timing issue was gone and everything seemed to work perfectly!  I don't have time to watch the whole show tonight though so I'll have to wait until tomorrow to see if it works the whole way through.

Thanks for your help, by the way. Is there anything else you'd like me to test?

My email address is aaron at ajexperience.com

**Comment by muzuiget** [comment] 2021-12-12 23:17
> I retested and it seems to work fine.

This what I need to test, the code you change is the adaptation code name:

```
if (hostname === 'www.primevideo.com') {
    return 'primevideo';
}
```

I can release a new version, with the following code changes:

```
if (hostname === 'www.primevideo.com' ||
    hostname === 'www.amazon.co.jp') {
    return 'primevideo';
}
```

> There seemed to be some timing issues during the show introduction, when the scene changed quickly and it was kind of a recap of the previous episodes and a preview of the current episode. Once the current episode actually started then the timing issue was gone and everything seemed to work perfectly! I don't have time to watch the whole show tonight though so I'll have to wait until tomorrow to see if it works the whole way through.

This is an expected behavior. Because there is no unique ID to pair the video file with the subtitle file, So always use the latest sniffed subtitle file. This happens when the video file is loaded earlier than the subtitle file.

**Comment by muzuiget** [comment] 2021-12-12 23:23
I think a good solution is the extension API can accept a _optional_ host permissions, so users won't be forced to accept all the permissions when installing or updating the extension. Safari does this, but neither Chrome nor Firefox.

**Comment by aaron13100** [comment] 2021-12-13 08:43
Honestly I don't think most people pay any attention to the permissions when they install a plugin, like the eula / terms of service for a website / program.

According to https://developer.chrome.com/docs/extensions/mv3/match_patterns/ there could be a pattern more specific for only videos. e.g. for https://www.amazon.co.jp/gp/video/detail/B09KN8F14R/ the pattern could be something like `https://www.amazon.co.jp/*/video/*` I guess? (untested)

I'm unfamiliar with how permissions work, but is https://developer.chrome.com/docs/extensions/reference/permissions/ what you're looking for? It says you can `Request the permissions from within a user gesture using permissions.request()`

**Comment by muzuiget** [comment] 2021-12-13 14:03
> Honestly I don't think most people pay any attention to the permissions when they install an extension, like the eula / terms of service for a website / program.

The permissions does matter. Not everyone has tech background about the extensions, when an extension updated with a new permission, Chrome will disable the extension and warn the users that some permissions have been added. Some users may uninstall the extension, and question the developer why require a new and unnessary permission. Especially `www.amazon.*` is more sensitive than other websites.

When you add `https://www.amazon.co.jp/*/video/*` to the `matches` fields, it request the `www.amazon.co.jp` **host** permission, there is no **url** permission, so Chrome will warn user the extension will access domain `www.amazon.co.jp` data. Some users don't know Primer Video can access in this domain, they may think Dualsub is stealing their shopping information.

In addition, different regions have different domain name variants, such as `www.amazon.fr` and `www.amazon.de`, etc., which is even more misleading. This is why I am unwilling to support the `www.amazone.*` domain name.

One solution is to publish another version with different permissions, but Chrome [does not allow this](https://developer.chrome.com/docs/webstore/program_policies/#spam).

> Repetitive Content: We don't allow any developer, related developer accounts, or their affiliates to submit multiple extensions that provide duplicate experiences or functionality on the Chrome Web Store. Extensions should provide value to users through the creation of unique content or services.

So the only solution is users modify the `manifest.json` and load with the developer mode.

**Comment by aaron13100** [comment] 2021-12-13 15:35
What about the `chrome.permissions.request({`?

> If the extension is updated automatically it will be disabled until the user agrees to the new permissions.
> This can be avoided by making the new feature optional and adding new permission updates to optional_permissions in the manifest.

from https://developer.chrome.com/docs/extensions/mv2/permission_warnings/

**Comment by muzuiget** [comment] 2021-12-14 06:42
This also not possible. 

The host permission is treated as forced when you put the url pattern in the `matches` of the `contents_scripts`.

**Comment by muzuiget** [comment] 2021-12-15 03:10
I change the adaptation code choosing as below:

```
if (hostname === 'www.primevideo.com' ||
    hostname.startsWith('www.amazon.')) {
    return 'primevideo';
}
``` 

So other `amazon` domain names are also available.

**Comment by aaron13100** [comment] 2021-12-15 07:08
That's good. 

I realize this is off-topic, so sorry. You can email me if you want, aaron at ajexperience.com. 

Just out of curiosity, how does the plugin get the translation result so fast?  I tried creating my own javascript solution that used the google cloud translation api, but when there were many subtitles to translate it sometimes took 1 to two seconds to get the translation result, at which time the subtitles had already disappeared and it was too late. 
regards

**Comment by muzuiget** [comment] 2021-12-15 07:28
> Just out of curiosity, how does the plugin get the translation result so fast? I tried creating my own javascript solution that used the google cloud translation api, but when there were many subtitles to translate it sometimes took 1 to two seconds to get the translation result, at which time the subtitles had already disappeared and it was too late.

This is the difference between Dualsub and other subtitle extensions.

Other subtitle extensions simply use functions such as `document.querySelecor` to get the subtitle text from the DOM node, and then translate it. One subtitle text sends an HTTP request, which of course will be delayed.

In Dualsub, multiple subtitle texts are translated through one HTTP request. This is why I need to implement subtitle processing pipelines, such as sniffing, parsing, translating, and rendering, to improve the user experience.

**Comment by aaron13100** [comment] 2021-12-20 19:28
What do you plan to when manifest v2 is no longer supported?

**Comment by muzuiget** [comment] 2021-12-23 13:13
v1.76.7 released, you only need change the `manifest.json` since this version.

**Comment by muzuiget** [comment] 2021-12-23 13:18
Only the Chrome Store has announced that it will stop supporting Manifest V2. Neither Firefox nor Edge stores. And Firefox and Safari only support Manifest V2.

So there is no plan to migrate to Manifest V3 now.

**Closed** 2021-12-30 07:32 UTC
